version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - RBL_SERVERS=${RBL_SERVERS}
      - RATE_LIMIT_COUNT=${RATE_LIMIT_COUNT}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW}
      - COMMON_DKIM_SELECTORS=${COMMON_DKIM_SELECTORS}
    volumes:
      - .:/app
    command: python app.py