version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/my-app/src
      - ./public:/app/my-app/public
      - ./package.json:/app/my-app/package.json
    volumes:
      - /app/my-app/node_modules
      - /app/my-app/build