version: '3.8'

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npx create-react-app . --template typescript && npm start"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true